name: jsonc
description: JSON with comments and trailing commas.
homepage: https://github.com/ubuntu-flutter-community/jsonc.dart
repository: https://github.com/ubuntu-flutter-community/jsonc.dart
issue_tracker: https://github.com/ubuntu-flutter-community/jsonc.dart/issues
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
